name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy  # Deploy when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Dockerfile and App to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no . ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app/

      - name: Install Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          EOF

      - name: Build and Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app/
            sudo docker build -t crm-ai-agent .
            sudo docker stop crm-ai-agent || true
            sudo docker rm crm-ai-agent || true
            sudo docker run -d --name crm-ai-agent -p 80:8000 crm-ai-agent
          EOF
